### ISSUE TITLE
Question index page not loading older questions

### ISSUE THREAD

**Issue by andela-oakinniranye** [zhishi-project/Zhishi-Frontend#45]
It seems the Question Index page is broken. 
Gives error: `Uncaught TypeError: g.getQuestions is not a function`

**Comment by andela-iamadi** [comment]
Yeah, continuous scroll not working on index page

**Comment by andela-iamadi** [comment]
I think @andela-ooduntan have fixed this. Other tickets that 'inherited' from his branch have this feature. QA confirm.
