### ISSUE TITLE
Textbox content not cleared after answering question

### ISSUE THREAD

**Issue by andela-oakinniranye** [zhishi-project/Zhishi-Frontend#76]
Steps to reproduce:
1. Go to a question
2. Enter the answer to the question
3. Click submit/post answer

Expected behaviour:
Answer should be posted and content of the text box should be cleared and answer should be surfaced on the page

Actual behaviour:
Content of the text box is not cleared, even though answer is posted, and answer does not surface on the page, until you refresh

**Comment by andela-ooduntan** [comment]
This issue is a duplicate of issue #77.
